# Generated by Django 5.1.3 on 2025-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('estudiante', 'periodo')},
        ),
    ]
