# Generated by Django 5.2.1 on 2025-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0003_docente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("curso", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254)),
                ("comentarios", models.TextField(blank=True, null=True)),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
