# Generated by Django 5.1.3 on 2025-05-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0004_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_inscripcion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
