# Generated by Django 5.1.3 on 2025-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0006_alter_inscripcion_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
