# Generated by Django 5.1.3 on 2025-05-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0007_inscripcion_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
