# Generated by Django 5.1.3 on 2025-05-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0008_alter_inscripcion_apellido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['estudiante', 'periodo'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='gestion_academica.estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.FloatField(help_text='Nota obtenida por el estudiante en el periodo'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre la calificación', null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='periodo',
            field=models.CharField(help_text="Periodo académico, e.g. '2024-1', '2024-2'", max_length=10),
        ),
    ]
