# Generated by Django 5.2.1 on 2025-05-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0010_estudiante_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmado", "Confirmado"),
                    ("rechazado", "Rechazado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
