# Generated by Django 5.1.3 on 2025-05-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0011_inscripcion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='programas',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='docente',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='correo',
            field=models.EmailField(default='Desconocido', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
