# Generated by Django 5.1.3 on 2025-05-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0012_remove_docente_programas_remove_docente_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
