# Generated by Django 5.1.3 on 2025-05-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0013_docente_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='correo',
            new_name='email',
        ),
    ]
